// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBqKv5yYEfEpvMkzPphttOloZ5baVAoqU',
    appId: '1:183779846888:web:b3cfdb56fe294874d4775d',
    messagingSenderId: '183779846888',
    projectId: 'pawhouse-5dd17',
    authDomain: 'pawhouse-5dd17.firebaseapp.com',
    storageBucket: 'pawhouse-5dd17.firebasestorage.app',
    measurementId: 'G-V0HWDQ22M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd6fWoRdmkv6EFkOaQV7PVahgZk5-RN1Y',
    appId: '1:183779846888:android:82e9d9e9253597cbd4775d',
    messagingSenderId: '183779846888',
    projectId: 'pawhouse-5dd17',
    storageBucket: 'pawhouse-5dd17.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBqKv5yYEfEpvMkzPphttOloZ5baVAoqU',
    appId: '1:183779846888:web:b3cfdb56fe294874d4775d',
    messagingSenderId: '183779846888',
    projectId: 'pawhouse-5dd17',
    authDomain: 'pawhouse-5dd17.firebaseapp.com',
    storageBucket: 'pawhouse-5dd17.firebasestorage.app',
    measurementId: 'G-V0HWDQ22M6',
  );
}
